version: '3.9'

services:
  # GOLANG
  golang:
    build: ./golang
    container_name: gobe
    ports:
      - "${GOLANG_PORT}:8080"
    depends_on: 
      - db
    networks:
      - app-network
    env_file:
      - ./.env.developer
    command: ["./main"]

  # NODE
    # node:
    #   build: ./node
    #   image: node:lts-alpine3.20
    #   container_name: nodeef
    #   ports:
    #     - "3003:3000"
    #   networks:
    #     - app-network
  
  # POSTGRES
  db:
    container_name: db
    image: postgres:alpine3.20
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
    

volumes:
  pg_data: {}

networks:
  app-network:
    external: true