version: '4.0'

services:
  # GOLANG
  golang:
    build: ./golang
    container_name: gobe
    ports:
      - "8080:8080"  
    depends_on: 
      - db
    networks:
      - app-network
    command: ["./main"]
  
  # POSTGRES
  db:
    container_name: db
    image: postgres:alpine3.20
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
    

volumes:
  pg_data: {}

networks:
  app-network:
    external: true